import { types } from "util";

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_LOADING = 'LOAD_CATEGORIES_LOADING';
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';
export const LOAD_ALL_CATEGORIES_SUCCESS = 'LOAD_ALL_CATEGORIES_SUCCESS';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_LOADING = 'DELETE_CATEGORY_LOADING';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_LOADING = 'EDIT_CATEGORY_LOADING';
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_LOADING = 'ADD_CATEGORY_LOADING';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';

export const LOAD_VENDORS_SUCCESS = 'LOAD_VENDORS_SUCCESS';
export const LOAD_VENDORS_LOADING = 'LOAD_VENDORS_LOADING';
export const LOAD_VENDORS_ERROR = 'LOAD_VENDORS_ERROR';

export const ADD_VENDORS_SUCCESS = 'ADD_VENDORS_SUCCESS';
export const ADD_VENDORS_LOADING = 'ADD_VENDORS_LOADING';
export const ADD_VENDORS_ERROR = 'ADD_VENDORS_ERROR';

export const EDIT_VENDOR_SUCCESS = 'EDIT_VENDOR_SUCCESS';
export const EDIT_VENDOR_LOADING = 'EDIT_VENDOR_LOADING';
export const EDIT_VENDOR_ERROR = 'EDIT_VENDOR_ERROR';

export const DELETE_VENDORS_SUCCESS = 'DELETE_VENDORS_SUCCESS';
export const DELETE_VENDORS_LOADING = 'DELETE_VENDORS_LOADING';
export const DELETE_VENDORS_ERROR = 'DELETE_VENDORS_ERROR';

export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCT_LOADING = 'LOAD_PRODUCT_LOADING';
export const LOAD_PRODUCT_ERROR = 'LOAD_PRODUCT_ERROR';

export const LOAD_SINGLE_PRODUCT_SUCCESS = 'LOAD_SINGLE_PRODUCT_SUCCESS';
export const LOAD_SINGLE_PRODUCT_LOADING = 'LOAD_SINGLE_PRODUCT_LOADING';
export const LOAD_SINGLE_PRODUCT_ERROR = 'LOAD_SINGLE_PRODUCT_ERROR';

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const ADD_PRODUCT_IMAGE_SUCCESS = 'ADD_PRODUCT_IMAGE_SUCCESS';

export const LOAD_SINGLE_PRODUCT_IMAGE_SUCCESS = 'LOAD_SINGLE_PRODUCT_IMAGE_SUCCESS';
export const LOAD_SINGLE_PRODUCT_IMAGE_LOADING = 'LOAD_SINGLE_PRODUCT_IMAGE_LOADING';
export const LOAD_SINGLE_PRODUCT_IMAGE_ERROR = 'LOAD_SINGLE_PRODUCT_IMAGE_ERROR';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_LOADING = 'LOAD_USER_LOADING';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_LOADING = "EDIT_USER_LOADING";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";