export const LOAD_VENDORS_SUCCESS = 'LOAD_VENDORS_SUCCESS';
export const LOAD_VENDORS_LOADING = 'LOAD_VENDORS_LOADING';
export const LOAD_VENDORS_ERROR = 'LOAD_VENDORS_ERROR';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_LOADING = 'LOAD_CATEGORIES_LOADING';
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_LOADING = 'DELETE_CATEGORY_LOADING';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_LOADING = 'EDIT_CATEGORY_LOADING';
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_LOADING = 'ADD_CATEGORY_LOADING';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';